---
title: "Decide-TB - SAM TDA RaPaed"
author: "Leyla Sophie Larsson"
date: '`r Sys.Date()`'
output:
  html_document:
    toc: true
    toc_depth: 4
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, fig.align = 'center')
# chunk options https://yihui.org/knitr/options/
```

```{r clear, include=FALSE}
rm(list = ls())
```

```{r rstan_options(auto_write = TRUE), include=FALSE}
# Import libraries

library(haven)
library(foreign)
library(gtsummary)
library(naniar)
library(lubridate)
library(lisa)
library(ggpubr)
library(gt)
library(knitr)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(hrbrthemes)

theme_set(theme_light(base_size = 9))
pal <- c("#FF8C00", "#A034F0", "#159090", "#152679")
```

```{r macros}
# Standard settings
dotsize <- 0.4 # Set dot size
```

```{r, include=FALSE}
# Import data
load("/users/leylasophielarsson/Desktop/Studies/Decide-TB/Analysis/Data/Decide-TB_SAM_Dataset.Rda")
load("/users/leylasophielarsson/Desktop/Studies/Decide-TB/Analysis/Data/Decide-TB_SAM_Dict.Rda")
```

**TDA**

The goal of this file is to run the generated Decide-TB dataset through the TB-Speed SAM Treatment Decision Algorithms as shown below to look at the numbers.

```{r}
# Create sub datasets with restrictions
tbspeed_sam <- subset(tbspeed_sam, SAM_V1==1)

sam_hosp_5 <- subset(tbspeed_sam, age<5)
sam_hosp_5 <- subset(sam_hosp_5, Q_404d1_Qes=="1. Yes")

sam_hosp <- subset(tbspeed_sam, Q_404d1_Qes=="1. Yes")

sam_5 <- subset(tbspeed_sam, age<5)

less2 <- subset(tbspeed_sam, age_cat == "< 2 years")
twoto5 <- subset(tbspeed_sam, age_cat == "2 - 5 years")
fiveto10 <- subset(tbspeed_sam, age_cat == "5 - 10 years")
more10 <- subset(tbspeed_sam, age_cat == "> 10 years")

uctli <- subset(tbspeed_sam, SiteID=="2. UctLi")
mmrc <- subset(tbspeed_sam, SiteID=="3. Mmrc")
ins <- subset(tbspeed_sam, SiteID=="4. Ins")
com <- subset(tbspeed_sam, SiteID=="5. CoM")
cmc <- subset(tbspeed_sam, SiteID=="6. CMC")

hivpos <- subset(tbspeed_sam, hivstatus=="HIV positive")
hivneg <- subset(tbspeed_sam, hivstatus=="HIV negative" | hivstatus=="Unknown")
```

## Flowchart

```{r}
# Prep data for flow chart 
library(dplyr)
library(tidyverse)

a <- subset(hivneg, !is.na("PersID")) %>% summarise(a = n()) 
b <- subset(hivneg, TBcontact == "Yes") %>% summarise(b = n())
c <- subset(hivneg, TBcontact == "No") %>% summarise(c = n())
d <- subset(hivneg, Symp_Score_Bin == "Yes" & TBcontact == "No") %>% summarise(d = n())
e <- subset(hivneg, Symp_Score_Bin == "No" & TBcontact == "No") %>% summarise(e = n())
e1 <- subset(hivneg, Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_max > 10) %>% summarise(e1 = n())
e2 <- subset(hivneg, Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_max <= 10) %>% summarise(e2 = n())
f <- subset(hivneg, Tx_Initiation_max=="Yes" | TBcontact == "Yes" | (Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_max > 10) | (Symp_Score_Bin == "Yes" & TBcontact == "No")) %>% summarise(f = n())
g <- subset(hivneg, Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_max <= 10) %>% summarise(g = n())

```

```{r}
library(consort)
library(labelled)
library(DiagrammeR)

# Define some sample data
data <- list(a=a$a, b=b$b, c=c$c, d=d$d, e=e$e, e1=e1$e1, e2=e2$e2, f=f$f, g=g$g)

DiagrammeR::grViz("
digraph graph_eos {

graph [layout = dot]

# node definitions with substituted label text
node [fontname = Helvetica, fontcolor = darkslategray,
        shape = rectangle, fixedsize = false, width = 2,
        style = filled, fillcolor = AliceBlue]
a [label = '@@1']
b [label = '@@2']
c [label = '@@3']
d [label = '@@4']
e [label = '@@5']
f [label = '@@6']
g [label = '@@7']
e1 [label = '@@8']
e2 [label = '@@9']

a -> b -> f;
a -> c -> d -> f;
c -> e -> e1 -> f;
e -> e2 -> g;

}

[1]: paste0('Number children < 5 hospitalised with SAM (n = ', data$a, ')')
[2]: paste0('History of contact with TB case (n = ', data$b, ')')
[3]: paste0('No contact with TB case (n = ', data$c, ')')
[4]: paste0('Symptom score > 10 (n = ', data$d, ')')
[5]: paste0('Symptom score ≤ 10 (n = ', data$e, ')')
[6]: paste0('Initiate TB treatment (n = ', data$f, ')')
[7]: paste0('Treat as appropriate and reassess (n = ', data$g, ')')
[8]: paste0('Overall score > 10 (n = ', data$e1, ')')
[9]: paste0('Overall score ≤ 10 (n = ', data$e2, ')')
")

```


```{r, include=FALSE}
rm(a,b,c,d,e,f,g,e1,e2)
```

### Diagnostic accuracy 

```{r}
TxInitiation <- subset(sam_hosp_5, Tx_Initiation_first=="Yes" | TBcontact == "Yes" | (Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first > 10) | (Symp_Score_Bin == "Yes" & TBcontact == "No"))
table(TxInitiation$DiagnClass)

TxInitiation_No <- subset(sam_hosp_5, Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first <= 10)
table(TxInitiation_No$DiagnClass)

```
```{r}
sam_hosp_5 <- sam_hosp_5 %>% mutate(Outcome = case_when(
 Tx_Initiation_first=="Yes" | TBcontact == "Yes" | (Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first > 10) | (Symp_Score_Bin == "Yes" & TBcontact == "No") ~ 1,
 Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first <= 10 ~ 0,
))

sam_hosp <- sam_hosp %>% mutate(Outcome = case_when(
 Tx_Initiation_first=="Yes" | TBcontact == "Yes" | (Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first > 10) | (Symp_Score_Bin == "Yes" & TBcontact == "No") ~ 1,
 Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first <= 10 ~ 0,
))

sam_5 <- sam_5 %>% mutate(Outcome = case_when(
 Tx_Initiation_first=="Yes" | TBcontact == "Yes" | (Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first > 10) | (Symp_Score_Bin == "Yes" & TBcontact == "No") ~ 1,
 Symp_Score_Bin == "No" & TBcontact == "No" & Overall_Score_first <= 10 ~ 0,
))
```

```{r}
table(sam_hosp_5$Outcome, sam_hosp_5$DiagnClass)
table(sam_hosp$Outcome, sam_hosp$DiagnClass)
table(sam_5$Outcome, sam_5$DiagnClass)
```


```{r}
library(epiR)
srs <- as.table(matrix(c(31,2,7,8), nrow = 2, byrow = TRUE))
rval_srs <- epi.tests(srs, conf.level = 0.95)
print(rval_srs)
```

### Distributions

```{r}
pal <- c("#212121","#003366", "#0066CC", "#3399FF", "#2196F3", "#CCE5FF")
pal_pro <- c("#B71C1C", "#0D47A1", "#2E7D32", "#212121", "#FF8C00")
```

``` {r, include=FALSE}
# function for the raincloud plots later. this function if you look at it calculates the median
add_sample <- function(x){
   return(c(y = max(x) + .025, 
            label = length(x)))
}
```

```{r}
decide <- subset(sam_hosp_5, TBcontact == "No")
decide_xpert <- subset(decide, !is.na(BinaryMaxResult))
decide_xpert$PCR_Semiquant <- factor(decide_xpert$PCR_Semiquant, 
                                 levels = c("Trace", "Very low", "Low", "Medium", "High"))
```

```{r}
order <- c("Confirmed", "Unconfirmed", "Unlikely", "Unclassifiable")
```


#### Xpert

##### Symptom score

``` {r}
library(colorspace)

decide_xpert %>% 
  group_by(PCR_Semiquant) %>% 
  ggplot(aes(x = fct_rev(PCR_Semiquant), y = Symp_Score)) + 
  ggdist::stat_halfeye(
    aes(color = PCR_Semiquant,
        fill = after_scale(lighten(color, .5))),
    adjust = .4, 
    width = .5, 
    .width = 0,
    justification = -.4, 
    point_color = NA) +
  geom_point(
    aes(color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS"))),
    fill = "white",
    shape = 21,
    stroke = .4,
    size = 2,
    position = position_jitter(seed = 1, width = .12)
  ) + 
  geom_point(
    aes(fill = PCR_Semiquant),
    color = "transparent",
    shape = 21,
    stroke = .4,
    size = 1,
    alpha = .2,
    position = position_jitter(seed = 1, width = .12)
  ) +
  geom_boxplot(
    aes(color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS")),
        fill = after_scale(desaturate(lighten(color, .8), .4))),
    width = .22, 
    outlier.shape = NA
  ) +
  scale_color_manual(values = pal, guide = "none") +
  scale_fill_manual(values = pal, guide = "none") +
  labs(
    x = NULL,
    y = "Score",
    title = "Distribution of symptom score by Xpert semiquantitative readout",
  ) + 
  coord_flip(xlim = c(1.2, NA), clip = "off") +
  annotate("text", x=2.5, y=-4.5, label= "*", color="white") +
  stat_summary(
    geom = "text",    
    fun.data = add_sample,
    aes(label = paste("n =", ..label..),
        color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Condensed",
    size = 3,
    hjust = 1,
    vjust = 3
  ) + 
  stat_summary(
    geom = "text",
    fun = "median",
    aes(label = round(..y.., 2),
        color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Mono",
    fontface = "bold",
    size = 4,
    vjust = -2.5
  )
```

##### Overall score

``` {r}
library(colorspace)

decide_xpert %>% 
  group_by(PCR_Semiquant) %>% 
  ggplot(aes(x = fct_rev(PCR_Semiquant), y = Overall_Score_max)) + 
  ggdist::stat_halfeye(
    aes(color = PCR_Semiquant,
        fill = after_scale(lighten(color, .5))),
    adjust = .4, 
    width = .5, 
    .width = 0,
    justification = -.4, 
    point_color = NA) +
  geom_point(
    aes(color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS"))),
    fill = "white",
    shape = 21,
    stroke = .4,
    size = 2,
    position = position_jitter(seed = 1, width = .12)
  ) + 
  geom_point(
    aes(fill = PCR_Semiquant),
    color = "transparent",
    shape = 21,
    stroke = .4,
    size = 1,
    alpha = .2,
    position = position_jitter(seed = 1, width = .12)
  ) +
  geom_boxplot(
    aes(color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS")),
        fill = after_scale(desaturate(lighten(color, .8), .4))),
    width = .22, 
    outlier.shape = NA
  ) +
  scale_color_manual(values = pal, guide = "none") +
  scale_fill_manual(values = pal, guide = "none") +
  labs(
    x = NULL,
    y = "Score",
    title = "Distribution of chest/Xpert score by Xpert semiquantitative readout",
  ) + 
  coord_flip(xlim = c(1.2, NA), clip = "off") +
  annotate("text", x=2.5, y=-4.5, label= "*", color="white") +
  stat_summary(
    geom = "text",    
    fun.data = add_sample,
    aes(label = paste("n =", ..label..),
        color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Condensed",
    size = 3,
    hjust = 1,
    vjust = 3
  ) + 
  stat_summary(
    geom = "text",
    fun = "median",
    aes(label = round(..y.., 2),
        color = PCR_Semiquant,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Mono",
    fontface = "bold",
    size = 4,
    vjust = -2.5
  )
```

#### By diagnostic classification

##### Symptoms score

``` {r}
library(colorspace)

decide %>% 
  mutate(DiagnClass = forcats::fct_relevel(DiagnClass, order)) %>%
  group_by(DiagnClass) %>% 
  ggplot(aes(x = fct_rev(DiagnClass), y = Symp_Score)) + 
  ggdist::stat_halfeye(
    aes(color = DiagnClass,
        fill = after_scale(lighten(color, .5))),
    adjust = .4, 
    width = .5, 
    .width = 0,
    justification = -.4, 
    point_color = NA) +
  geom_point(
    aes(color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS"))),
    fill = "white",
    shape = 21,
    stroke = .4,
    size = 2,
    position = position_jitter(seed = 1, width = .12)
  ) + 
  geom_point(
    aes(fill = DiagnClass),
    color = "transparent",
    shape = 21,
    stroke = .4,
    size = 1,
    alpha = .2,
    position = position_jitter(seed = 1, width = .12)
  ) +
  geom_boxplot(
    aes(color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS")),
        fill = after_scale(desaturate(lighten(color, .8), .4))),
    width = .22, 
    outlier.shape = NA
  ) +
  scale_color_manual(values = pal, guide = "none") +
  scale_fill_manual(values = pal, guide = "none") +
  labs(
    x = NULL,
    y = "Score",
    title = "Distribution of symptom score by diagnostic classification",
  ) + 
  coord_flip(xlim = c(1.2, NA), clip = "off") +
  annotate("text", x=2.5, y=-4.5, label= "*", color="white") +
  stat_summary(
    geom = "text",    
    fun.data = add_sample,
    aes(label = paste("n =", ..label..),
        color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Condensed",
    size = 3,
    hjust = 1,
    vjust = 3
  ) + 
  stat_summary(
    geom = "text",
    fun = "median",
    aes(label = round(..y.., 2),
        color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Mono",
    fontface = "bold",
    size = 4,
    vjust = -2.5
  )
```

##### Overall score

``` {r}
library(colorspace)

decide %>% 
  mutate(DiagnClass = forcats::fct_relevel(DiagnClass, order)) %>%
  group_by(DiagnClass) %>% 
  ggplot(aes(x = fct_rev(DiagnClass), y = Overall_Score_max)) + 
  ggdist::stat_halfeye(
    aes(color = DiagnClass,
        fill = after_scale(lighten(color, .5))),
    adjust = .4, 
    width = .5, 
    .width = 0,
    justification = -.4, 
    point_color = NA) +
  geom_point(
    aes(color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS"))),
    fill = "white",
    shape = 21,
    stroke = .4,
    size = 2,
    position = position_jitter(seed = 1, width = .12)
  ) + 
  geom_point(
    aes(fill = DiagnClass),
    color = "transparent",
    shape = 21,
    stroke = .4,
    size = 1,
    alpha = .2,
    position = position_jitter(seed = 1, width = .12)
  ) +
  geom_boxplot(
    aes(color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS")),
        fill = after_scale(desaturate(lighten(color, .8), .4))),
    width = .22, 
    outlier.shape = NA
  ) +
  scale_color_manual(values = pal, guide = "none") +
  scale_fill_manual(values = pal, guide = "none") +
  labs(
    x = NULL,
    y = "Score",
    title = "Distribution of chest/xpert score by diagnostic classification",
  ) + 
  coord_flip(xlim = c(1.2, NA), clip = "off") +
  annotate("text", x=2.5, y=-4.5, label= "*", color="white") +
  stat_summary(
    geom = "text",    
    fun.data = add_sample,
    aes(label = paste("n =", ..label..),
        color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Condensed",
    size = 3,
    hjust = 1,
    vjust = 3
  ) + 
  stat_summary(
    geom = "text",
    fun = "median",
    aes(label = round(..y.., 2),
        color = DiagnClass,
        color = after_scale(darken(color, .1, space = "HLS"))),
    family = "Roboto Mono",
    fontface = "bold",
    size = 4,
    vjust = -2.5
  )
```